name: PHP CI

on:
  push:
    branches:
      - development

jobs:
  fetch:
    runs-on: [php-test]
    env:
      TEST_APP_ENV: ${{ secrets.TEST_APP_ENV}}
      TEST_APP_SECRET: ${{ secrets.TEST_APP_SECRET}}
      TEST_DATABASE_URL: ${{ secrets.TEST_DATABASE_URL}}
      TEST_KERNEL_CLASS: ${{ secrets.TEST_KERNEL_CLASS}}
      TEST_CORS_ALLOW_ORIGIN: ${{ secrets.TEST_CORS_ALLOW_ORIGIN}}
      TEST_MESSENGER_TRANSPORT_DSN: ${{ secrets.TEST_MESSENGER_TRANSPORT_DSN}}
    steps:
      - name: Clone Repository
        run: |
          cd /home/dev/docker-lemp 
          rm -rf mehana-lian
          git clone https://github.com/L37sg0/mehana-lian.git ./mehana-lian 
          cd mehana-lian
          git checkout development
          echo "APP_ENV=$TEST_APP_ENV" >> .env
          echo "APP_SECRET=$TEST_APP_SECRET" >> .env
          echo "DATABASE_URL=$TEST_DATABASE_URL" >> .env
          echo "KERNEL_CLASS=$TEST_KERNEL_CLASS" >> .env
          echo "CORS_ALLOW_ORIGIN=$TEST_CORS_ALLOW_ORIGIN" >> .env
          echo "MESSENGER_TRANSPORT_DSN=$TEST_MESSENGER_TRANSPORT_DSN" >> .env

  build-back:
    runs-on: [php-test]
    needs: [fetch]
    steps:
      - name: Composer Install
        run: |
          cd /home/dev/docker-lemp
          docker-compose exec -T app composer -d mehana-lian install

      - name: Database Setup
        run: |
          cd /home/dev/docker-lemp
          docker-compose exec -T app mehana-lian/bin/console doctrine:database:create --if-not-exists
          docker-compose exec -T app mehana-lian/bin/console doctrine:migrations:migrate

      - name: Database Fixtures
        run: |
          cd /home/dev/docker-lemp
          docker-compose exec -T app mehana-lian/bin/console doctrine:fixtures:load --group=AppFixtures --group=AdminFixtures

  build-front:
    runs-on: [php-test]
    needs: [fetch]
    steps:
      - name: NPM Install
        run: |
          cd /home/dev/docker-lemp
          docker-compose exec -T app npm install --prefix mehana-lian

      - name: NPM Build
        run: |
          cd /home/dev/docker-lemp
          docker-compose exec -T app npm run dev --prefix mehana-lian      

  test:
    runs-on: [php-test]
    needs: [build-back]
    steps:
      - name: Run tests
        run: |
          cd /home/dev/docker-lemp
          docker-compose exec -T app mehana-lian/bin/phpunit -c mehana-lian/phpunit.xml.dist

  quality-assurance:
    runs-on: [php-test]
    needs: [build-back]
    steps:
      - name: QA
        run: |
          cd /home/dev/docker-lemp
          docker-compose exec -T app mehana-lian/vendor/bin/phpstan analyse -c mehana-lian/phpstan.dist.neon

