name: PHP CI

on:
  push:
    branches:
      - development

jobs:
  fetch:
    runs-on: [php-test, php-test-2]
    steps:
      - name: Clone Repository
        run: |
          cd /home/dev/docker-lemp && 
          rm -rf mehana-lian &&
          git clone https://github.com/L37sg0/mehana-lian.git ./mehana-lian &&
          cp ./mehana-lian/.env.test ./mehana-lian/.env

  build-back:
    runs-on: [php-test, php-test-2]
    needs: [fetch]
    steps:
      - name: Composer Install
        run: |
          cd /home/dev/docker-lemp &&
          docker-compose exec -T app composer -d mehana-lian install

      - name: Database Setup
        run: |
          cd /home/dev/docker-lemp &&
          docker-compose exec -T app mehana-lian/bin/console doctrine:database:create --if-not-exists &&
          docker-compose exec -T app mehana-lian/bin/console doctrine:migrations:migrate

      - name: Database Fixtures
        run: |
          cd /home/dev/docker-lemp &&
          docker-compose exec -T app mehana-lian/bin/console doctrine:fixtures:load

  build-front:
    runs-on: [php-test, php-test-2]
    needs: [fetch]
    steps:
      - name: NPM Install
        run: |
          cd /home/dev/docker-lemp &&
          docker-compose exec -T app npm install --prefix mehana-lian

      - name: NPM Build
        run: |
          cd /home/dev/docker-lemp &&
          docker-compose exec -T app npm run dev --prefix mehana-lian      

  test:
    runs-on: [php-test, php-test-2]
    needs: [build-back]
    steps:
      - name: Run tests
        run: |
          cd /home/dev/docker-lemp &&
          docker-compose exec -T app mehana-lian/bin/phpunit mehana-lian/tests/
##
#  quality:
#    runs-on: [php-test, php-test-2]]
#