name: PHP CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    container: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
