name: PHP CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
#      - name: Checkout Repository
#        uses: actions/checkout@v2
      - name: Check environment is running
#        run: docker-compose exec app php -v
        run: cd /home/dev/docker-lemp && docker-compose exec -T app php -v