name: PHP CD

on:
  push:
    branches:
      - main

jobs:
  fetch:
    runs-on: [php-live]
    env:
      LIVE_APP_ENV: ${{ secrets.LIVE_APP_ENV}}
      LIVE_APP_SECRET: ${{ secrets.LIVE_APP_SECRET}}
      LIVE_DATABASE_URL: ${{ secrets.LIVE_DATABASE_URL}}
      LIVE_KERNEL_CLASS: ${{ secrets.LIVE_KERNEL_CLASS}}
      LIVE_CORS_ALLOW_ORIGIN: ${{ secrets.LIVE_CORS_ALLOW_ORIGIN}}
      LIVE_MESSENGER_TRANSPORT_DSN: ${{ secrets.LIVE_MESSENGER_TRANSPORT_DSN}}
      LIVE_API_ENDPOINT: ${{ secrets.LIVE_API_ENDPOINT }}
      LIVE_API_HOST: ${{ secrets.LIVE_API_HOST }}
      LIVE_JWT_PASSPHRASE: ${{ secrets.LIVE_JWT_PASSPHRASE }}
    steps:
      - name: Clone Repository
        run: |
          cd /home/dev/docker-lemp/mehana-lian 
          git fetch
          git pull
          rm -rf .env
          echo "APP_ENV=$LIVE_APP_ENV" >> .env
          echo "APP_SECRET=$LIVE_APP_SECRET" >> .env
          echo "DATABASE_URL=$LIVE_DATABASE_URL" >> .env
          echo "KERNEL_CLASS=$LIVE_KERNEL_CLASS" >> .env
          echo "CORS_ALLOW_ORIGIN=$LIVE_CORS_ALLOW_ORIGIN" >> .env
          echo "MESSENGER_TRANSPORT_DSN=$LIVE_MESSENGER_TRANSPORT_DSN" >> .env
          echo "API_ENDPOINT=$LIVE_API_ENDPOINT" >> .env
          echo "API_HOST=$LIVE_API_HOST" >> .env
          echo "JWT_SECRET_KEY=%kernel.project_dir%/config/jwt/private.pem" >> .env
          echo "JWT_PUBLIC_KEY=%kernel.project_dir%/config/jwt/public.pem" >> .env
          echo "JWT_PASSPHRASE=$LIVE_JWT_PASSPHRASE" >> .env

  build-back:
    runs-on: [php-live]
    needs: [fetch]
    steps:
      - name: Composer Install
        run: |
          cd /home/dev/docker-lemp
          docker-compose exec -T app composer -d mehana-lian install
          docker-compose exec -T app composer -d mehana-lian dumpautoload
          docker-compose exec -T app composer dump-env prod -d mehana-lian/

      - name: Database Setup
        run: |
          cd /home/dev/docker-lemp
          docker-compose exec -T app mehana-lian/bin/console doctrine:database:create --if-not-exists
          docker-compose exec -T app mehana-lian/bin/console doctrine:migrations:migrate

  build-api-auth:
    runs-on: [ php-live ]
    needs: [ build-back ]
    steps:
      - name: Generate Keypair lexik:jwt
        run: |
          cd /home/dev/docker-lemp
          docker-compose exec -T app mehana-lian/bin/console lexik:jwt:generate-keypair --skip-if-exists

  build-front:
    runs-on: [php-live]
    needs: [fetch]
    steps:
      - name: NPM Install
        run: |
          cd /home/dev/docker-lemp
          docker-compose exec -T app npm install --prefix mehana-lian

      - name: NPM Build
        run: |
          cd /home/dev/docker-lemp
          docker-compose exec -T app npm run dev --prefix mehana-lian
  

  test:
    runs-on: [php-live]
    needs: [ build-back, build-api-auth ]
    steps:
      - name: Run tests
        run: |
          cd /home/dev/docker-lemp
          docker-compose exec -T app mehana-lian/bin/phpunit -c mehana-lian/phpunit.xml.dist --exclude-group=deprecated
