name: PHP CD

on:
  push:
    branches:
      - main

jobs:
  fetch:
    runs-on: [php-live]
    steps:
      - name: Clone Repository
        run: |
          cd /home/dev/docker-lemp/mehana-lian && 
          git fetch &&
          git pull

  build-back:
    runs-on: [php-live]
    needs: [fetch]
    steps:
      - name: Composer Install
        run: |
          cd /home/dev/docker-lemp &&
          docker-compose exec -T app composer -d mehana-lian install &&
          docker-compose exec -T app composer -d mehana-lian dumpautoload

      - name: Database Setup
        run: |
          cd /home/dev/docker-lemp &&
          docker-compose exec -T app mehana-lian/bin/console doctrine:database:create --if-not-exists &&
          docker-compose exec -T app mehana-lian/bin/console doctrine:migrations:migrate

  build-front:
    runs-on: [php-live]
    needs: [fetch]
    steps:
      - name: NPM Install
        run: |
          cd /home/dev/docker-lemp &&
          docker-compose exec -T app npm install --prefix mehana-lian

      - name: NPM Build
        run: |
          cd /home/dev/docker-lemp &&
          docker-compose exec -T app npm run dev --prefix mehana-lian